from typing import Iterator, Protocol
from .models import AppendResult, ResumeState, SessionEvent, SessionMetadata


class SessionStore(Protocol):
    def create_session(self, *, workspace: str, title: str, model: str | None = None,
                       session_id: str | None = None, **initial) -> SessionMetadata: ...
    def append_event(self, event: SessionEvent) -> AppendResult: ...
    def get_session(self, session_id: str) -> SessionMetadata: ...
    def load_events(self, session_id: str, *, after_event_id: str | None = None) -> Iterator[SessionEvent]: ...
    def list_sessions(self, *, workspace: str | None = None, query: str | None = None,
                      archived: bool = False, limit: int | None = 50) -> list[SessionMetadata]: ...
    def rename_session(self, session_id: str, title: str) -> None: ...
    def archive_session(self, session_id: str, archived: bool = True) -> None: ...
    def delete_session(self, session_id: str) -> None: ...
    def resume_session(self, session_id: str) -> ResumeState: ...
    def fork_session(self, session_id: str, *, at_event_id: str, title: str) -> SessionMetadata: ...
